### ISSUE TITLE
clear all domains

### ISSUE THREAD

**Issue by bogdansoare** [andyrichardson/tipple#54]
would be useful to have a clear all domains function when you want to wipe all data for example on a logout, something similar to [apollo client reset store](https://www.apollographql.com/docs/react/v2.5/api/apollo-client/#ApolloClient.resetStore)

**Comment by andyrichardson** [comment]
I can see this being useful. Do you have an example of when this would be a good use case?

**Comment by bogdansoare** [comment]
When an user logouts from the app and you want to clear all the data in the cache

**Comment by andyrichardson** [comment]
I think in this case, you would want to create a new client entirely. As your top-level state changes (in this case, the auth state) your components should react accordingly.

If you use an AuthContext for this, you can update the client after a login component updates the context.

```tsx
const App: FC = () => {
  const { token } = useContext(AuthContext);
  const client = useRef<typeof TippleClient>();

  useLayoutEffect(() => {
    client.current = createClient({
      baseUrl: 'http://localhost:5000/api',
      fetchOptions: {
        headers: { 'Content-Type': 'application/json', 'Some-Token-Header': token }
      }
    })
  }, [token])

  const routing = useMemo(() => {
    if (token === undefined) {
      return <LoginPage />
    }

    return (
      <>
        <Route to="/" component={HomePage} />
        <Route to="/users" component={UsersPage} />
      </>
    )
  }, [token]);

  return (
    <TippleProvider client={client.current}>
      {routing}
    </TippleProvider>;
  );
}


```

**Comment by bogdansoare** [comment]
Nice idea 👍.

One question is why the use of `useLayoutEffect` instead of `useEffect` ?

Also like the use of `useMemo` 👏

**Comment by andyrichardson** [comment]
I believe useLayoutEffect will be executed synchronously (guaranteed before render).

In fairness, you could probably replace the ref with state or a useMemo call - I'd need to double check
